### ISSUE TITLE
markdown export: `(())` not removed for block references

### ISSUE THREAD

**Issue by tiensonqin** [logseq/mldoc#28] opened 2021-03-18 13:14 UTC
![Screenshot-2021-03-18_21:07:29](https://user-images.githubusercontent.com/479169/111631657-a0a56880-882e-11eb-80b6-08dbd9d8578b.png)

I noticed three issues for markdown export:
1. `(())` not removed for block references
2. block embed output has the wrong indentation.
3. page embed are not exported

**Comment by RCmerci** [comment] 2021-03-18 15:40
1. `(())` between block title is the expected output because it means it's a block-reference. But it looks unnecessary?
2. the embed-block starts with `##`(level=2), so indent level is added by 2 (4 spaces)
3. didn't reproduce here, and there is no embed-page in the above test page, right?

**Comment by RCmerci** [comment] 2021-03-19 06:40
1，2 is fixed here #29

**Comment by RCmerci** [comment] 2021-03-21 09:38
3 should be fixed now #31 & https://github.com/logseq/logseq/pull/1515

**Closed** 2021-03-30 07:54 UTC
